export default abstract class Response {
  public static readonly HTTP_CONTINUE: number = 100
  public static readonly HTTP_SWITCHING_PROTOCOLS: number = 101
  public static readonly HTTP_PROCESSING: number = 102 // RFC2518
  public static readonly HTTP_EARLY_HINTS: number = 103 // RFC8297
  public static readonly HTTP_OK: number = 200
  public static readonly HTTP_CREATED: number = 201
  public static readonly HTTP_ACCEPTED: number = 202
  public static readonly HTTP_NON_AUTHORITATIVE_INFORMATION: number = 203
  public static readonly HTTP_NO_CONTENT: number = 204
  public static readonly HTTP_RESET_CONTENT: number = 205
  public static readonly HTTP_PARTIAL_CONTENT: number = 206
  public static readonly HTTP_MULTI_STATUS: number = 207 // RFC4918
  public static readonly HTTP_ALREADY_REPORTED: number = 208 // RFC5842
  public static readonly HTTP_IM_USED: number = 226 // RFC3229
  public static readonly HTTP_MULTIPLE_CHOICES: number = 300
  public static readonly HTTP_MOVED_PERMANENTLY: number = 301
  public static readonly HTTP_FOUND: number = 302
  public static readonly HTTP_SEE_OTHER: number = 303
  public static readonly HTTP_NOT_MODIFIED: number = 304
  public static readonly HTTP_USE_PROXY: number = 305
  public static readonly HTTP_RESERVED: number = 306
  public static readonly HTTP_TEMPORARY_REDIRECT: number = 307
  public static readonly HTTP_PERMANENTLY_REDIRECT: number = 308 // RFC7238
  public static readonly HTTP_BAD_REQUEST: number = 400
  public static readonly HTTP_UNAUTHORIZED: number = 401
  public static readonly HTTP_PAYMENT_REQUIRED: number = 402
  public static readonly HTTP_FORBIDDEN: number = 403
  public static readonly HTTP_NOT_FOUND: number = 404
  public static readonly HTTP_METHOD_NOT_ALLOWED: number = 405
  public static readonly HTTP_NOT_ACCEPTABLE: number = 406
  public static readonly HTTP_PROXY_AUTHENTICATION_REQUIRED: number = 407
  public static readonly HTTP_REQUEST_TIMEOUT: number = 408
  public static readonly HTTP_CONFLICT: number = 409
  public static readonly HTTP_GONE: number = 410
  public static readonly HTTP_LENGTH_REQUIRED: number = 411
  public static readonly HTTP_PRECONDITION_FAILED: number = 412
  public static readonly HTTP_REQUEST_ENTITY_TOO_LARGE: number = 413
  public static readonly HTTP_REQUEST_URI_TOO_LONG: number = 414
  public static readonly HTTP_UNSUPPORTED_MEDIA_TYPE: number = 415
  public static readonly HTTP_REQUESTED_RANGE_NOT_SATISFIABLE: number = 416
  public static readonly HTTP_EXPECTATION_FAILED: number = 417
  public static readonly HTTP_I_AM_A_TEAPOT: number = 418 // RFC2324
  public static readonly HTTP_MISDIRECTED_REQUEST: number = 421 // RFC7540
  public static readonly HTTP_UNPROCESSABLE_ENTITY: number = 422 // RFC4918
  public static readonly HTTP_LOCKED: number = 423 // RFC4918
  public static readonly HTTP_FAILED_DEPENDENCY: number = 424 // RFC4918
  public static readonly HTTP_TOO_EARLY: number = 425 // RFC-ietf-httpbis-replay-04
  public static readonly HTTP_UPGRADE_REQUIRED: number = 426 // RFC2817
  public static readonly HTTP_PRECONDITION_REQUIRED: number = 428 // RFC6585
  public static readonly HTTP_TOO_MANY_REQUESTS: number = 429 // RFC6585
  public static readonly HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE: number = 431 // RFC6585
  public static readonly HTTP_UNAVAILABLE_FOR_LEGAL_REASONS: number = 451 // RFC7725
  public static readonly HTTP_INTERNAL_SERVER_ERROR: number = 500
  public static readonly HTTP_NOT_IMPLEMENTED: number = 501
  public static readonly HTTP_BAD_GATEWAY: number = 502
  public static readonly HTTP_SERVICE_UNAVAILABLE: number = 503
  public static readonly HTTP_GATEWAY_TIMEOUT: number = 504
  public static readonly HTTP_VERSION_NOT_SUPPORTED: number = 505
  public static readonly HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL: number = 506 // RFC2295
  public static readonly HTTP_INSUFFICIENT_STORAGE: number = 507 // RFC4918
  public static readonly HTTP_LOOP_DETECTED: number = 508 // RFC5842
  public static readonly HTTP_NOT_EXTENDED: number = 510 // RFC2774
  public static readonly HTTP_NETWORK_AUTHENTICATION_REQUIRED: number = 511 // RFC6585
}
